cleaner code, a bit less FP style

diff --git a/ylog b/ylog
--- a/ylog
+++ b/ylog
@@ -1,8 +1,10 @@
 #!/usr/bin/env zsh
 # command line note taking system by directories
 
-err(){print -- $* >&2; exit 1}
 log(){print -- $*}
+err(){print -- $* >&2; exit 1}
+
+# Usage
 app="${0:t}"
 (($#==0)) && err "$app is a command line note taking tool
 
@@ -12,10 +14,16 @@ app="${0:t}"
     $app todo some text -- prepent a todo box ([ ]) before the note
     $app some text      -- add the note to the log file"
 
+# default logfilename
 logfilename=".log"
 
+# evil global variables, my Haskell fu is crying!
+# in ZSH it would be a pain not to use them
+logfile=""
+subdir=""
+
 # return the subdir of the project
-subdir(){
+checkLogfile(){
     local logfiledir=$PWD
     subdir=""
     while [[ ! -e $logfiledir/$logfilename ]]; do
@@ -27,45 +35,41 @@ subdir(){
         fi
         logfiledir="${logfiledir:h}"
     done
-    print -- $subdir
+    subdir=$subdir
+    logfile=$logfiledir/$logfilename
 }
 
-# return the logfile
-logfile(){
-    local logfiledir=$PWD
-    while [[ ! -e $logfiledir/$logfilename ]]; do
-        [[ $logfiledir = / ]] && err "Couldn't find a $logfilename file"
-        logfiledir="${logfiledir:h}"
-    done
-    print -- $logfiledir/$logfilename
-}
-
-checkLogfile(){ logfile }
-
+# Add a message to the log file
 addMessage(){
-    checkLogfile
-    local logpath=$(logfile)
-    local subdir=$(subdir)
     {
         print -n "[$(date +"%d-%m-%Y")] "
         [[ $subdir != "" ]] && print -n "($subdir) "
         print -- $*
-    } >> $logpath
+    } >> $logfile
 }
 
 
+# Special case for init
+[[ $1 = "init" ]] && {
+    if touch $logfilename; then
+        log "log initialized"
+        exit 0
+    else
+        err "can't create $logfilename file"
+    fi
+}
+
+# if all over cases, search the log file and current subdir
+checkLogfile
 case $1 in
-    init) touch .log;;
-    show) checkLogfile ; cat $(logfile);;
-    edit) checkLogfile
-          [[ $EDITOR = "" ]] && EDITOR="vi"
-          $EDITOR $(logfile);;
+    show) cat $logfile;;
+    edit) [[ $EDITOR = "" ]] && EDITOR="vi"
+          $EDITOR $logfile;;
     todo) shift; message="[ ] $*"; addMessage $message ;;
-    reset)  checkLogfile
-            print -n -- "Do you really want to remove all your notes? (y/n): "
+    reset)  print -n -- "Do you really want to remove all your notes? (y/n): "
             read answer
             case ${answer:l} in
-            y|yes) echo > $(logfile);print "log file emptied";;
+            y|yes) echo > $logfile;print "log file emptied";;
             *) exit 0
             esac ;;
     *) addMessage $* ;;
